# Declare a name for this job
#$ -N SPCE_0

# Request that email is sent when job has started, ended, aborted, or suspended
#$ -m beas
#$ -M bm@berkeley.edu

# Run program and save logfiles in the current working directory
#$ -cwd

if [ "x" == "x$WINDOW_LOWER_BOUND" ] || [ "x" == "x$WINDOW_UPPER_BOUND" ] ; then
     echo "window bounds not set"
else
     echo "WINDOW_LOWER_BOUND: $WINDOW_LOWER_BOUND"
	 echo "WINDOW_UPPER_BOUND: $WINDOW_UPPER_BOUND"
fi


# Run the program
./SPCE

exit 0