#!/bin/bash

NWINDOWS=5
WINDOWSPACING=1.5
WINDOWWIDTH=2.0
MINIMUMH=4.0
HISTOGRAMFILE=umbrella_rdf
NITERATIONS=300
DATAFILE=window

./mbar $NWINDOWS $WINDOWSPACING $WINDOWWIDTH $MINIMUMH $HISTOGRAMFILE $NITERATIONS $DATAFILE
