#!/bin/bash

$MAIN_N = "A"
$N1 = $MAIN_N"1"
$N2 = $MAIN_N"2"
$N3 = $MAIN_N"3"
$N4 = $MAIN_N"4"
$N5 = $MAIN_N"5"
$N6 = $MAIN_N"6"

qsub -v WINDOW_LOWER_BOUND=0.0,WINDOW_UPPER_BOUND=5.0,SIM_NAME=$N1 -N $N1 qsub.sh
qsub -v WINDOW_LOWER_BOUND=4.5,WINDOW_UPPER_BOUND=7.0,SIM_NAME=$N2 -N $N2 qsub.sh
qsub -v WINDOW_LOWER_BOUND=6.5,WINDOW_UPPER_BOUND=9.0,SIM_NAME=$N3 -N $N3 qsub.sh
qsub -v WINDOW_LOWER_BOUND=8.5,WINDOW_UPPER_BOUND=11.0,SIM_NAME=$N4 -N $N4 qsub.sh
qsub -v WINDOW_LOWER_BOUND=10.5,WINDOW_UPPER_BOUND=13.0,SIM_NAME=$N5 -N $N5 qsub.sh
qsub -v WINDOW_LOWER_BOUND=12.5,WINDOW_UPPER_BOUND=15.0,SIM_NAME=$N6 -N $N6 qsub.sh
